name: openswitch-alphanetworks-snx-60a0-486f
version: 0.3.0-1
summary: OpenSwitch NOS for an alphanetworks-snx-60a0-486f host.
description: A standalone version of the OpenSwitch NOS (www.openswitch.net) for the Alphanetworks SNX-60A0-486F host.

parts:
  openswitch:
    plugin: x-openswitch
#    source: https://github.com/ops-snappy/ops-build.git
    source: /work/ops-build
    platform: alphanetworks-snx-60a0-486f
    stage-packages: [ libyaml-cpp0.3-dev, zlib1g, libatomic1 ]
